# Generated by Django 5.1.3 on 2024-11-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='product_image/'),
        ),
    ]
