# Generated by Django 5.1.3 on 2024-11-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_purchase_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(upload_to='qrimage/')),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
    ]
