# Generated by Django 5.1.3 on 2024-11-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_paymentqr_alter_purchase_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='mobile_number',
            field=models.CharField(default='your number', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='name',
            field=models.CharField(default='your name', max_length=100),
        ),
    ]
