# Generated by Django 5.1.3 on 2024-11-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_purchase_mobile_number_purchase_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='tmp/product_image/'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_screenshot',
            field=models.ImageField(upload_to='tmp/payment_screenshots/'),
        ),
    ]
