# Generated by Django 5.1.3 on 2024-11-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_product_image_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentqr',
            name='qr_image',
            field=models.URLField(default='https://i.postimg.cc/MHHY0gBd/qrcode.jpg', max_length=5000),
        ),
    ]
