# Generated by Django 5.1.3 on 2024-11-21 04:58

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_paymentqr_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='mobile_number',
            field=models.CharField(default='your number', max_length=10, validators=[main.models.validate_mobile_number]),
        ),
    ]
