# Generated by Django 5.1.3 on 2024-11-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_purchase_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_screenshot',
            field=models.ImageField(upload_to='payment_screenshots/'),
        ),
    ]
